In [1]:
import numpy as np

In [3]:
import numpy as np
print(np.__version__)

2.5.1


In [1]:
#!pip list | grep numpy
# windows에는 기본적으로 grep대시 findstr이 탑재되어 있음
!uv  pip list | findstr numpy   

numpy                     2.5.1


In [3]:
import time

# 1,000만 개의 원소를 가진 파이썬 리스트 생성
py_list = list(range(10000000))

# 연산 시간 측정시작
start_time = time.time()

# for 루프 또는 컴프리헨션을 이용한 각 원소 2배 연산
result_list = [x * 2 for x in py_list]

print(f"파이썬 리스트 소요 시간: {time.time() - start_time:.4f} 초")

파이썬 리스트 소요 시간: 0.7744 초


In [6]:
np.arange(10)  # ([start,] stop [,step])

# python을 이용한 계산
%time sum(range(1000000))

NameError: name 'np' is not defined

In [8]:
import numpy as np    # numpy를 np 를 관례적으로 alias 

# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64 -> 64는 비트  1=8비트 

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64


배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [10]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.dtype)            # int64 : 정수 64bit => 8byte

<class 'numpy.ndarray'>
int64


In [12]:
import numpy as np

int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # array([1., 2., 3.]) -> float 실수
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


In [13]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # print(a.shape)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [14]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [16]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  
                     [[5,6][7,8]]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

IndentationError: unexpected indent (3953675044.py, line 4)

In [18]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # print(a.shape)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [20]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [22]:
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [24]:
a - np.zeros((2,3))
print(a)

[0. 0. 0.]


In [25]:
a  = np.ones(3)
print(a)

[1. 1. 1.]


In [27]:
a = np.ones((2,3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
np.eye(3)
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
a = np.eye(3, 4, k=1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### np.full((행,열)), 값)

- 지정한 크기의 배열을 생성하고 채울 값을 지정한다.

In [ ]:
a = np.full((2,2,), [1, 3]) # np.full(shape, fill_value)
print(a)


[[1 3]
 [1 3]]


In [ ]:
a = np.full((2,2), [[1], [2]]) # np.full(shape, fill_value)
print(a)


[[1 1]
 [2 2]]


In [37]:
a = np.full((2,2,), [[1,2],[3,4]])  # np.full(shape, fill_value)
print(a)

[[1 2]
 [3 4]]


np.empty((행, 열))

In [40]:
a = np.empty(3)
print(a) # [1. 1. 1.]

[1. 1. 1.]


### linspace

- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세 번째 num인자 값이 생략되여 있으므로 start와 end 계산해서 default 50이 생성된다.
- linspace(start, end, num)
- linspace (0, 49) #num의 default value 50

In [44]:
a = np.linspace(0, 49)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [47]:
a  = np.linspace(0, 5)
print(a)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [50]:
a = np.linspace(0, 5)
print(a)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


### **arange**

np.arange([**start**, ]stop, [step, ]dtype=**None**)

- start: 생성할 배열의 시작 값 (기본값은 0)
- stop: 생성할 배열의 종료 값 (이 값은 포함되지 않음)
- step: 숫자 사이의 간격 (기본값은 1)
- dtype: 생성할 배열의 데이터 타입 (옵션)

In [ ]:
# 기본 사용법
# 0부터 9까지의 숫자 배열 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
# 시작 값과 종료 값 설정
arr = np.arange(3, 10) # 3부터 9까지
print(arr)

[3 4 5 6 7 8 9]


In [59]:
# 간격 설정
arr = np.arange(1, 10, 2) # 1부터 9까지 2씩 증가
print(arr)

[1 3 5 7 9]


In [60]:
# 실수 간격 사용
arr = np.arange(0, 1, 0.1)  # 0부터 1까지 0.1씩 증가
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### _like

- _like가 붙으면 shape이 같게 만들어진다.
- 연산하기 위해서 shape을 맞춰야 하는 경우가 있다.


In [63]:
a = np.array([[1.,2.,3.,],[4., 5., 6.]])
print(a)

b = np.zeros_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [64]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.empty_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


난수(Random) 생성과 분포 빌드

In [68]:
# 1부터 46 미만의 범위에서 무작위 로또 번호를 숫자를 닮은 6개 정수 생성
lotto_numbers = np.random.randint(1, 46, size=6)
print(lotto_numbers)

[13  4 31 17  7 43]


In [71]:
# numpy 도움말
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [73]:
#Copy

a = [1, 2, 3]        # list
b = a
print(b)
print(a is b )        # 메모리 주소 비교 True
b[0] = 7
print(a)               # [7, 2, 3]           
print(b)                # [7, 2, 3]

[1, 2, 3]
True
[7, 2, 3]
[7, 2, 3]


In [ ]:
# 1차원 일 경우
a = [1,2,3]
b = a.copy()          # deep copy : copy() ★ 중요
id(a)                 # 133162358434304
id(b)                 # 133162358425280
print(a is b)         # 주소 비교 False
print(a == b)         # 값 비교 True

b[0] = 8
# a는 안바뀐다.
print(a)               # [1, 2, 3]
print(b)               # [8, 2, 3]
print(a is b)          # 메모리 주소 비교  False
print(a == b)          # 값 비교           False

False
True
[1, 2, 3]
[8, 2, 3]
False
False


In [75]:
# 2차원일 경우
a = [[1,2,3]]
print(type(a))           # list

b = a.copy()
print(id(a))              # 133162358428608
print(id(b))              # 133162358989568

print(a is b)             # False
print(a == b)             # True 

b[0][0] = 10
print(a[0])               # [10, 2, 3]
print(b[0])               # [10, 2, 3]

<class 'list'>
2696231469120
2696229603840
False
True
[10, 2, 3]
[10, 2, 3]


In [77]:
import copy

a = [[1,2,3]]
# list가 2차원일때 deep copy을 하기 위해서 copy모듈에 있는 
# deepcopy메소드를 사용한다.
b = copy.deepcopy(a) 

print(a[0] is b[0])        # 메모리 주소 False
print(a[0] == b[0])        # 값 True

b[0][0] = 10

print(a[0] is b[0])         # 메모리 주소 False
print(a[0] == b[0])         # 값 False

print(a)                    # [[1, 2, 3]]
print(b)                    # [[10, 2, 3]]


False
True
False
False
[[1, 2, 3]]
[[10, 2, 3]]


[:] 는 전체라는 뜻이다.

슬라이싱 방식으로 1차 리스트일때는 재할당하면 deep copy가 된다.

슬라이싱 방식으로 2차 리스트 이상인 경우는 shallow copy가 발생된다.

In [79]:
a = [1,2,3]
b = a[:]
print(a)                      # [1,2,3]
print(b)                      # [1,2,3]

b[0] = 10
print(a)                      # [1, 2, 3]
print(b)                      # [10, 2, 3]

a = [[1,2,3]]
b = a[:]
print(a is b)                 # False
print(a == b)                 # True

 # 메모리 주소 비교  => 2차원일때 deepcopy 가 발생되지 않음
print(a[0][0] is b[0][0])                    #True
print(a[0][0] == b[0][0])  # 값비교           #True


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[10, 2, 3]
False
True
True
True


In [80]:
a = b = np.array([1,2,3])
print(a is b)                         # True
print(a == b)                         # [ True  True  True] 각각 요소가 나온다 ★

a[0] = 100
print(a[0])                           # 100
print(b[0])                           # 100


a = np.array([1,2,3])
b = a.copy()

print(a is b)                           # 메모리 주소 False      
print(a == b)                           # 값 [ True  True  True]

True
[ True  True  True]
100
100
False
[ True  True  True]


2. 배열의 인덱싱, 슬라이싱 및 형태 변형

2) 2차원 매트릭스 인덱싱 ([행, 열]) 슬라이싱 [:]매우 중요 ★

- 리스트의 중첩 구조(`arr[][]`)와 달리, 넘파이는 단일 대괄호 내부에 쉼표 하나로 행과 열을 동시에 제어 (`arr[행, 열]`).
- 0번째 축(`axis=0`, 행)과 1번째 축(`axis=1`, 열)의 인덱스가 각각 독립적이고 유기적으로 결합되어 작동

## 2.2 불리언 인덱싱 (Boolean Indexing) 
-> 자주 사용★★

- 조건 필터링 (예: 특정 값 이상인 데이터만 골라내기)
- 배열의 각 원소에 조건식(예: `arr > 5`)을 적용하여 참(`True`)과 거짓(`False`)으로 구성된 조건 배열 생성
- 생성된 불리언 배열을 기존 배열의 인덱스로 주입하여 `True`인 위치의 값만 필터링하여 반환

In [82]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
bool_mask = arr > 5
print(arr[arr > 5])  # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [83]:
arr  = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

bool_mark = arr > 5
print(arr[bool_mark])

[6 7 8 9]


In [84]:
arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6,7],
    [8, 9, 10, 11]
])

axis_ABC = ['A', 'A', 'B', 'C', 'C']

bool_mask = arr[axis_ABC == 'A']
print(arr[bool_mask])  # 출력: [[0,1,2,3], [4,5,6,7]]
                        

[]


## 2.3 팬시 인덱싱 (Fancy Indexing)

- 특정 인덱스 배열을 전달하여 비연속적인 데이터 추출하기
- 정수형 레이블이나 인덱스 번호가 담긴 리스트/배열을 전달하여 원하는 위치의 데이터를 한 번에 추출
- 연속적이지 않고 무작위로 떨어져 있는 특정 행이나 열을 임의로 골라낼 때 유용하게 활용

In [85]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 팬시 인덱싱: 0번 행과 2번 행만 선택하여 추출
print(arr[[0, 2]])     # 출력: [[1, 2, 3], [7, 8, 9]]

[[1 2 3]
 [7 8 9]]


In [86]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])

print(arr[[1, 2]])     # [[3, 4,5], [6, 7, 8]]
# print(arr[[1 : 3]])  -> x -> 비연속적인 데이터를 가져오기 때문에 : 에러 나옴
# print(arr[1:3]) -> 가능

print(arr[[-1, -2]])    # [[12, 13, 14], [9, 10, 11]]

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


2.4   팬시 인덱싱과 불리언 차이

In [94]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)


# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]       

# fancy indexing은 원래 3차원 그대로 가져온다.
a[[0]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

ellipsis

- …(ellipsis)은 이후의 모든 것을 의미한다.

In [100]:
# 
a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)

type(...)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ellipsis

In [101]:
a[[0], :, :] # b[[0]]은  b[[0], :, :]의 단축 표현이다.
```
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

SyntaxError: invalid syntax (3494116768.py, line 2)

In [104]:
a[:, 1, :]
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [106]:
a[:, [1], :]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [108]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [111]:
b = a [:, [1], :]
b.shape

(2, 1, 4)

In [113]:
a[:,:,[1]]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [115]:
np.arange(1000)

np.set_printoptions(edgeitems=6)

2.5 배열의 형태 변형 (Reshaping) 
`reshape()`, `flatten()`, `ravel()의 차이점 및 활용`

 1) reshape 함수와 -1의 의미

- 원소의 총 개수를 유지하면서 배열의 차원과 모양(`shape`)을 자유자재로 변경하는 핵심 함수
- 형태 지정 시 한 축에 `-1`을 대입하면, 전체 원소 개수를 기반으로 나머지 축의 크기를 컴퓨터가 자동으로 계산하여 배치

 2) 1차원 평탄화: flatten과 ravel의 차이점

- `flatten()`: 다차원 배열을 1차원 배열로 완전히 풀어버리며, 원본과 분리된 새로운 메모리 '복사본(Copy)'을 생성


In [119]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')  
print(f' {arr is dap}') 

[1 2 3 4]
메모리 공유 확인:: False
 False


In [121]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') # 같은 메모리이기 때문에 True
print(arr_1d is arr_2d)  # arr_1d 1차원, arr_2d 2차원이라 False



메모리 공유 확인:: True
False


## 2.6 배열의 결합 및 분할

`np.concatenate()`, `np.vstack()`, `np.hstack()`으로 데이터 합치기


In [123]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.r_[a,b])                              # [[1 2 3][4 5 6]]

v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')                      # v_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)    # axis = 0
print(f'concat_row:: {concat_row}')            # concat_row:: [[1 2 3][4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3]
 [4 5 6]]
v_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [[1 2 3]
 [4 5 6]]


In [125]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.c_[a,b])                              # [[1 2 3 4 5 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [[1 2 3 4 5 6]]

concat_col = np.concatenate((a, b), axis=1)    # axis = 1
print(f'concat_col:: {concat_col}')            # concat_col:: [[1 2 3 4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3 4 5 6]]
h_col:: [[1 2 3 4 5 6]]
concat_col:: [[1 2 3 4 5 6]]


In [127]:
a = np.array([1, 2, 3])
print(f'a={a}')           # a=[1 2 3]      

b = np.array([4, 5, 6])
print(f'b={b}')           # b=[4 5 6]

print(np.r_[a,b])


a=[1 2 3]
b=[4 5 6]
[1 2 3 4 5 6]


In [130]:
a = np.array([1, 2, 3])
print(f'a={a}')                                # a=[1 2 3]

b = np.array([4, 5, 6])
print(f'b={b}')                                # b=[4 5 6]

print(np.c_[a,b])                              # [[1 4]
                                            #  [2 5]
                                                #  [3 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [1 2 3 4 5 6]

# AxisError: axis 1 is out of bounds for array of dimension 1 ->> 범위를 벗어나서 사용하면 안됌
concat_col = np.concatenate((a, b), axis=1)    # axis = 1

a=[1 2 3]
b=[4 5 6]
[[1 4]
 [2 5]
 [3 6]]
h_col:: [1 2 3 4 5 6]


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [136]:
# 2차원이면 3차원으로 증가한다.
b = np.stack((x,y), axis = 0)
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print(b)

(2, 3, 2)
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


배열 분할하기

In [138]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [139]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

print(np.vsplit(x, 3))
print(np.vsplit(x, (1,2)))

print(np.split(x, 3, axis=0))
print(np.split(x, (1, 2), axis=0))

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


In [141]:
arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]
row_vec

array([[1, 2, 3]])

### ② `ravel()` / `flatten()` / `reshape(-1)` (평탄화: 1차원 변환)

다차원 배열을 **1차원 배열로 완전히 펼칠 때** 사용합니다.

- `ravel()`: 원본의 뷰(View)를 반환 (메모리 절약, 속도 빠름)
- `flatten()`: 원본을 복사(Copy)하여 반환
- `reshape(-1)`: 가장 범용적인 평탄화 방식

3. 벡터화 연산과 브로드캐스팅 (핵심 구간) 중요★

3.2 브로드캐스팅 (Broadcasting) 규칙: 서로 크기가 다른 배열 간의 연산이 가능해지는 마법 같은 원리와 조건 중요 ★

### **3.2.1  브로드캐스팅의 규칙 (Broadcasting Rules)**

두 배열 A와 B가 연산 가능하려면, **뒤쪽 차원(가장 오른쪽 축)부터 비교**하여 다음 **두 조건 중 하나**를 만족해야  한다.
① **두 차원의 크기가 같다.**
②  **둘 중 하나의 차원 크기가 1이다.** (스칼라도 크기가 1인 차원으로 취급됨)

💡 **비교 예시:**

- `Shape (4, 3)` 과 `Shape (3,)`
$\rightarrow$ 뒤쪽 차원부터 비교: `3 == 3` (같음) / 앞 차원은 1로 간주되어 연산 가능!
- `Shape (4, 3)` 과 `Shape (4,)`
$\rightarrow$ 뒤쪽 차원 비교: `3 != 4` (다르고 1도 아님) $\rightarrow$ **연산 불가능 (Error)**

### 3.2.3 브로드캐스팅의 장점

**① 메모리 효율성:** 데이터를 실제로 메모리에 복사하여 늘리지 않고, 연산 시점에 가상으로 맞춰 처리하므로 **메모리를 거의 차지하지 않는다.**

**② 연산 속도:** 반복문(`for` 문) 없이 C언어 수준에서 한 번에 연산하므로 **속도가 훨씬 빠릅니다.**

**③ 코드의 간결성:** 데이터 형상을 맞추기 위한 부가적인 코드가 줄어들어 **가독성이 좋아집니다.**

3.5 위치 찾기: np.argmax(), np.argmin()을 활용한 최대/최소값의 인덱스 번호 추출 중요★

In [143]:
# 1. 1차원 배열 생성 (색인/Index: 0~5)
#    값(Value)   : [5, 4, 3, 2, 1, 0]
#    인덱스(Index): [0, 1, 2, 3, 4, 5]
x = np.array([5, 4, 3, 2, 1, 0])

# 2. 인덱스 추출 함수 연산
argmax_val = np.argmax(x)  # 가장 큰 값의 인덱스(위치)  #★중요
argmin_val = np.argmin(x)  # 가장 작은 값의 인덱스(위치)


## 4.3 **선형대수 기초 (Linear Algebra)**:

In [ ]:

# 1. 벡터 및 행렬 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# 2. 벡터 내적 (Dot Product)
dot_product = np.dot(v1, v2)
print("Vector Dot Product:")
print(dot_product)
# 출력: 32 (1*4 + 2*5 + 3*6)

# 3. 행렬 곱셈 (Matrix Multiplication)  머신러닝에서 매우 중요!!★
matrix_mul = np.matmul(A, B) # 또는 A @ B
print("\nMatrix Multiplication (A @ B):")
print(matrix_mul)
# 출력:
# [[19 22]
#  [43 50]]

# 4. 전치 행렬 (Transpose Matrix)
A_transpose = A.T
print("\nTranspose of Matrix A:")
print(A_transpose)
# 출력:
# [[1 3]
#  [2 4]]

# 5. 역행렬 (Inverse Matrix)
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(A_inv)
# 출력:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 6. 행렬식 (Determinant)
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:")
print(det_A)
# 출력: -2.0 (1*4 - 2*3)

# 7. 고유값 및 고유벡터 (Eigenvalues & Eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
# 출력: [-0.37228132  5.37228132]

print("\nEigenvectors of A:")
print(eigenvectors)
# 출력:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]

Vector Dot Product:
32

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix A:
-2.0000000000000004

Eigenvalues of A:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors of A:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


In [149]:
# 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)

1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


In [150]:
# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)

1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]
